name: mpd-splines-inference
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - patchelf
  - numpy
  - scipy
  - matplotlib
  - plotly
  - scikit-learn
  - pillow
  - pandas
  - h5py
  - ffmpeg
  - pip:
      - pyyaml
      - tensorboard
      - tqdm
      - ConfigArgParse
      - shapely
      - setuptools
      - joblib
      - sentence_transformers
      - wandb
      - trimesh
      - mesh_to_sdf
      - seaborn
      - tabulate
      - einops
      - torchdiffeq
      - torch-summary
      - pygame
      - gitpython
      - scikit-video
      - opencv-python
      - moviepy
      - hydra
      - urdfpy
      - pybullet
      - dirsync
      - colour
      - pre-commit
      - black
      - dotmap
      - vendi_score
      - torch_kmeans
      - networkx
      - empy==3.3.4
      - rospkg
      - catkin_pkg
      - example-robot-data
      - imutils
      - opencv-contrib-python